//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2084_Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int id { get; set; }
        public byte result { get; set; }
        public string notes { get; set; }
        public string map { get; set; }
        public int opponent_1 { get; set; }
        public int opponent_2 { get; set; }
    
        public virtual Opponent Opponent { get; set; }
        public virtual Opponent Opponent1 { get; set; }
    }
}
